### ISSUE TITLE
PDFLib empty?

### ISSUE THREAD

**Issue by JensSam** [Shogobg/rn-pdf-lib#24]
Hi, 

I get an error message saying Error: [TypeError: Cannot read property 'measureText' of null].

I'm on RN 0.72.4

I get the exact same error with the original react-native-pdf-lib

Thanks
//Jens

**Comment by Shogobg** [comment]
Hello @JensSam ,
can you paste your code how you're using the library?

I have the following and it works:
```JavaScript
import PDFLib, {PDFDocument, PDFPage} from '@shogobg/react-native-pdf';

PDFLib.measureText('My Centered Title', 'Franklin Gothic Medium', 14);
```
